### ISSUE TITLE
Not building for android on Apple silicon

### ISSUE THREAD

**Issue by michaelgobbers** [MadBrains/Mad-Pay-Flutter#37]
Looks like there are issues getting this to build on a Mac with Apple silicon:
Output from building this for my android emulator:
```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
lib/main.dart:1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mad_pay_android:generateDebugProto'.
> Could not resolve all files for configuration ':mad_pay_android:protobufToolsLocator_protoc'.
   > Could not find protoc-3.14.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.14.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.14.0/protoc-3.14.0-osx-aarch_64.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Exception: Gradle task assembleSandboxDebug failed with exit code 1
Exited (sigterm)
```

**Comment by mit-73** [comment]
Hi @michaelgobbers, I added changes to the [apple_silicon](https://github.com/MadBrains/Mad-Pay-Flutter/tree/apple_silicon/packages/mad_pay) branch, could you test it?

To do this, just add these lines to pubspec.yaml:

```
dependency_overrides:
  mad_pay_android:
    git:
      url: git@github.com:MadBrains/Mad-Pay-Flutter.git
      ref: apple_silicon
      path: packages/mad_pay_android
```

I would like to hear the results of your test. If all goes well, I will update the package in pub.dev :)
